theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
title: KingJuliusss Blog
description: Welcome to my blog
author: King JJJuliusss
layout: null
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;rss version=&quot;2.0&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
    &lt;channel&gt;
        &lt;title&gt;{{ site.title &#124; xml_escape }}&lt;/title&gt;
        &lt;description&gt;{{ site.description &#124; xml_escape }}&lt;/description&gt;
        &lt;link&gt;{{ site.url }}{{ site.baseurl }}/&lt;/link&gt;
        &lt;atom:link href=&quot;{{ &quot;/feed.rbloggers.xml&quot; &#124; prepend: site.baseurl &#124; prepend: site.url }}&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot;/&gt;
        &lt;pubDate&gt;{{ site.time &#124; date_to_rfc822 }}&lt;/pubDate&gt;
        &lt;lastBuildDate&gt;{{ site.time &#124; date_to_rfc822 }}&lt;/lastBuildDate&gt;
        &lt;generator&gt;Jekyll v{{ jekyll.version }}&lt;/generator&gt;
        {% for post in site.tags[&quot;R&quot;] %}
            &lt;item&gt;
                &lt;title&gt;{{ post.title &#124; xml_escape }}&lt;/title&gt;
                &lt;author&gt;your_blog_email@host.com (Your Name)&lt;/author&gt;
                &lt;description&gt;{{ post.content &#124; xml_escape }}&lt;/description&gt;
                &lt;pubDate&gt;{{ post.date &#124; date_to_rfc822 }}&lt;/pubDate&gt;
                &lt;link&gt;{{ post.url &#124; prepend: site.baseurl &#124; prepend: site.url }}&lt;/link&gt;
                &lt;guid isPermaLink=&quot;true&quot;&gt;{{ post.url &#124; prepend: site.baseurl &#124; prepend: site.url }}&lt;/guid&gt;
                {% for tag in post.tags %}
                &lt;category&gt;{{ tag &#124; xml_escape }}&lt;/category&gt;
                {% endfor %}
                {% for cat in post.categories %}
                &lt;category&gt;{{ cat &#124; xml_escape }}&lt;/category&gt;
                {% endfor %}
            &lt;/item&gt;
        {% endfor %}
    &lt;/channel&gt;
&lt;/rss&gt;
</code></pre>
