theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
title: KingJuliusss Blog
description: Welcome to my blog
author: King JJJuliusss
layout: null
url: https://kingjuliusss.github.io/RT-Dose-Response/
